web/api/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns(
    '',
    url(r'^v1/', include('api.v1.urls')),
)

web/main/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.sitemaps import views as sitemaps_views
from django.views.decorators.cache import cache_page

from blog.sitemaps import BlogSitemap
from nouns.views import ChannelDetail
from profiles.sitemaps import ProfileSitemap
from premises.sitemaps import ArgumentSitemap, PremiseSitemap

admin.autodiscover()

sitemaps = {
    'blog': BlogSitemap(),
    'user': ProfileSitemap(),
    'argument': ArgumentSitemap(),
    'premise': PremiseSitemap()
}

urlpatterns = patterns('',
    url(r'^', include('newsfeed.urls')),
    url(r'^', include('premises.urls')),
    url(r'^', include('profiles.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^nouns/', include('nouns.urls')),
    url(r'^channels/(?P<slug>[-\w]+)$',
        ChannelDetail.as_view(), name="channel_detail"),
    url(r'^', include('social_auth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('api.urls')),

    # Sitemap
    url(r'^sitemap\.xml$',
        cache_page(86400)(sitemaps_views.index),
        {'sitemaps': sitemaps, 'sitemap_url_name': 'sitemaps'}),
    url(r'^sitemap-(?P<section>.+)\.xml$',
        cache_page(86400)(sitemaps_views.sitemap),
        {'sitemaps': sitemaps}, name='sitemaps'),
)

web/premises/urls.py
from django.conf.urls import patterns, url
from premises.views import (ContentionDetailView, HomeView,
                            ArgumentCreationView, PremiseCreationView,
                            PremiseDeleteView, ContentionJsonView,
                            PremiseEditView, ArgumentUpdateView,
                            ArgumentPublishView, ArgumentUnpublishView,
                            ArgumentDeleteView, AboutView, NewsView,
                            UpdatedArgumentsView, ReportView, RemoveReportView,
                            ControversialArgumentsView, TosView, SearchView,
                            NotificationsView, PremiseSupportView, PremiseUnsupportView,
                            StatsView, FallaciesView, FeaturedJSONView, NewsJSONView,
                            RandomArgumentView)


urlpatterns = patterns('',
   url(r'^$', HomeView.as_view(), name='home'),
   url(r'^notifications$', NotificationsView.as_view(), name='notifications'),
   url(r'^featured.json$', FeaturedJSONView.as_view(), name='contentions_featured_json'),
   url(r'^news.json$', NewsJSONView.as_view(), name='contentions_latest_json'),
   url(r'^news$', NewsView.as_view(),
       name='contentions_latest'),
   url(r'^search$', SearchView.as_view(),
       name='contentions_search'),
   url(r'^random$', RandomArgumentView.as_view(),
       name='contentions_random'),
   url(r'^updated$', UpdatedArgumentsView.as_view(),
       name='contentions_updated'),
   url(r'^controversial', ControversialArgumentsView.as_view(),
       name='contentions_controversial'),
   url(r'^stats$', StatsView.as_view(),
       name='contentions_stats'),
    url(r'^fallacies$', FallaciesView.as_view(),
       name='fallacies'),
   url(r'^about$',
       AboutView.as_view(),
       name='about'),
   url(r'^tos$',
       TosView.as_view(),
       name='tos'),
   url(r'^new-argument$',
       ArgumentCreationView.as_view(),
       name='new_argument'),
   url(r'^(?P<slug>[\w-]+)/edit$',
        ArgumentUpdateView.as_view(),
        name='contention_edit'),
   url(r'^(?P<slug>[\w-]+)\.json$',
        ContentionJsonView.as_view(),
        name='contention_detail_json'),
   url(r'^(?P<slug>[\w-]+)$',
        ContentionDetailView.as_view(),
        name='contention_detail'),
   url(r'^(?P<slug>[\w-]+)/(?P<premise_id>[\d+]+)$',
        ContentionDetailView.as_view(),
        name='premise_detail'),
   url(r'^(?P<slug>[\w-]+)/premises/(?P<pk>[0-9]+)/unsupport',
        PremiseUnsupportView.as_view(),
        name='unsupport_premise'),
   url(r'^(?P<slug>[\w-]+)/premises/(?P<pk>[0-9]+)/support',
        PremiseSupportView.as_view(),
        name='support_premise'),
   url(r'^(?P<slug>[\w-]+)/premises/(?P<pk>[0-9]+)/delete',
        PremiseDeleteView.as_view(),
        name='delete_premise'),
   url(r'^(?P<slug>[\w-]+)/premises/(?P<pk>[0-9]+)/report',
        ReportView.as_view(),
        name='report_premise'),
   url(r'^(?P<slug>[\w-]+)/premises/(?P<pk>[0-9]+)/unreport',
        RemoveReportView.as_view(),
        name='unreport_premise'),
   url(r'^(?P<slug>[\w-]+)/premises/(?P<pk>[0-9]+)/new',
        PremiseCreationView.as_view(),
        name='insert_premise'),
   url(r'^(?P<slug>[\w-]+)/premises/(?P<pk>[0-9]+)',
        PremiseEditView.as_view(),
        name='edit_premise'),
   url(r'^(?P<slug>[\w-]+)/premises/new',
        PremiseCreationView.as_view(),
        name='new_premise'),
    url(r'^(?P<slug>[\w-]+)/publish',
        ArgumentPublishView.as_view(),
        name='contention_publish'),
    url(r'^(?P<slug>[\w-]+)/unpublish',
        ArgumentUnpublishView.as_view(),
        name='contention_unpublish'),
    url(r'^(?P<slug>[\w-]+)/delete',
        ArgumentDeleteView.as_view(),
        name='contention_delete'),
)

web/nouns/models.py
from uuid import uuid4
from unidecode import unidecode

from django.db import models
from django.utils.encoding import smart_unicode
from django.conf import settings
from django.template.defaultfilters import slugify
from django.utils.functional import curry
from django.utils.translation import ugettext_lazy as _, get_language
from anora.templatetags.anora import CONSONANT_SOUND, VOWEL_SOUND
from i18n.utils import normalize_language_code

from nouns.utils import get_synsets, get_lemmas, from_lemma


class Noun(models.Model):
    text = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, blank=True)
    language = models.CharField(max_length=25)
    is_active = models.BooleanField(default=True)

    class Meta:
        unique_together = (("text", "language"),)

    def __unicode__(self):
        return smart_unicode(self.text).title()

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = slugify(unidecode(self.text))
            duplications = Noun.objects.filter(slug=slug,
                                               language=self.language)
            if duplications.exists():
                self.slug = "%s-%s" % (slug, uuid4().hex)
            else:
                self.slug = slug
        return super(Noun, self).save(*args, **kwargs)

    @classmethod
    def from_synset(cls, synset):
        lemmas = synset.lemma_names()
        text = lemmas[0]
        keywords = lemmas[1:]
        noun, created = cls.objects.get_or_create(
            text=from_lemma(text),
            defaults={
                'is_active': False,
                'language': normalize_language_code(get_language())
            })
        for keyword in keywords:
            noun.add_keyword(from_lemma(keyword))
        return noun

    def update_with_wordnet(self, update_antonyms=True):
        synsets = get_synsets(self.text)

        if not synsets:
            return

        for synset in synsets:
            path = synset.hypernym_paths()[0]
            parents = path[:-1]
            parent = self
            for hypernym in reversed(parents):
                noun = Noun.from_synset(hypernym)
                parent.add_hypernym(noun)
                parent = noun

            for holonym in synset.part_holonyms():
                noun = Noun.from_synset(holonym)
                self.add_holonym(noun)

            for holonym in synset.member_holonyms():
                noun = Noun.from_synset(holonym)
                self.add_holonym(noun)

        for lemma in get_lemmas(self.text):
            if lemma != self.text:
                self.add_keyword(lemma)

        if not update_antonyms:
            return

        for synset in synsets:
            for lemma in synset.lemmas():
                for antonym in lemma.antonyms():
                    noun = Noun.from_synset(antonym.synset())
                    self.add_antonym(noun)
                    noun.update_with_wordnet(update_antonyms=False)

    def add_keyword(self, text):
        keyword, created = self.keywords.get_or_create(text=text)
        return keyword

    def active_keywords(self):
        return self.keywords.filter(is_active=True)

    def active_contentions(self):
        language = normalize_language_code(get_language())
        return self.contentions.filter(
            is_published=True,
            language=language
        ).order_by('?')

    def indirect_contentions(self):
        from premises.models import Contention  # to avoid circular import
        language = normalize_language_code(get_language())
        nouns = self.out_relations.values_list('target', flat=True)
        return Contention.objects.filter(
            language=language,
            is_published=True,
            nouns__in=nouns
        ).order_by('?')

    @models.permalink
    def get_absolute_url(self):
        return 'nouns_detail', [self.slug]

    def serialize(self):
        return {
            'title': self.text,
            'absolute_url': self.get_absolute_url()
        }

    def hypernyms(self):
        return self.out_relations.filter(relation_type='hypernym')

    def hyponyms(self):
        return self.in_relations.filter(relation_type='hypernym')

    def add_relation(self, target, relation_type=None):
        relation, created = (
            self.out_relations.get_or_create(
                target=target, relation_type=relation_type)
        )
        return relation

    add_hypernym = curry(add_relation, relation_type="hypernym")
    add_holonym = curry(add_relation, relation_type="holonym")
    add_antonym = curry(add_relation, relation_type="antonym")


class Keyword(models.Model):
    """
    Keywords for matching contentions.
    """
    noun = models.ForeignKey(Noun, related_name="keywords")
    text = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)

    def __unicode__(self):
        return smart_unicode(self.text)


class Relation(models.Model):
    """
    Holds the relationships of contentions.

        - is a (hypernym)
        - part of (holonym)
        - opposite (antonym)
        - same_as (synonym)

    """
    HYPERNYM = "hypernym"
    HOLONYM = "holonym"
    ANTONYM = "antonym"
    HYPONYM = "hyponym"
    MERONYM = "meronym"

    TYPES = (
        (HYPERNYM, _('is a')),
        (HOLONYM, _('part of')),
        (ANTONYM, _('opposite with')),
    )

    source = models.ForeignKey(Noun, related_name="out_relations")
    target = models.ForeignKey(Noun, related_name="in_relations")
    relation_type = models.CharField(max_length=25, choices=TYPES)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return smart_unicode(self.relation_type)

    def reverse_type(self):
        return {
            Relation.HYPERNYM: Relation.HYPONYM,
            Relation.HOLONYM: Relation.MERONYM,
            Relation.ANTONYM: Relation.ANTONYM
        }.get(self.relation_type)

    def get_reverse_type_display(self):
        return {
            Relation.HYPONYM: _("whole of"),
            Relation.MERONYM: _("whole of"),
            Relation.ANTONYM: _("opposite with")
        }.get(self.reverse_type())

    def relation_type_label(self):
        if (self.relation_type == Relation.HYPERNYM
                and self.target.language == 'en'):
            text = unicode(self.target)
            return ('is an' if not CONSONANT_SOUND.match(text)
                               and VOWEL_SOUND.match(text)
                    else 'is a')
        return self.get_relation_type_display()


class Channel(models.Model):
    title = models.CharField(max_length=255)
    slug = models.CharField(max_length=255)
    nouns = models.ManyToManyField('Noun', null=True, blank=True)
    order = models.IntegerField()
    language = models.CharField(max_length=255, blank=True, null=True)
    is_featured = models.BooleanField(max_length=255, default=False)

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = slugify(unidecode(self.text))
            self.slug = slug
        return super(Channel, self).save(*args, **kwargs)

    def __unicode__(self):
        return smart_unicode(self.title)

    @models.permalink
    def get_absolute_url(self):
        return 'channel_detail', [self.slug]

    def serialize(self):
        return {
            'title': self.title,
            'absolute_url': self.get_absolute_url()
        }

web/premises/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from premises.constants import MAX_PREMISE_CONTENT_LENGTH
from premises.mixins import FormRenderer
from premises.models import Contention, Premise, Report


class ArgumentCreationForm(FormRenderer, forms.ModelForm):
    class Meta:
        model = Contention
        fields = ['title', 'owner', 'sources']


class PremiseCreationForm(FormRenderer, forms.ModelForm):

    class Meta:
        model = Premise
        fields = ['premise_type', 'text', 'related_argument', 'sources']
        widgets = {
            'premise_type': forms.RadioSelect,
            'related_argument': forms.TextInput,
            'text': forms.Textarea(attrs={
                'maxlength': MAX_PREMISE_CONTENT_LENGTH
            })
        }

    def clean(self):
        form_data = self.cleaned_data
        if not form_data['related_argument'] and not form_data['text']:
            raise ValidationError(_('You should write a premise or link an argument.'))
        return form_data


class PremiseEditForm(PremiseCreationForm):
    class Meta:
        model = Premise
        fields = ['premise_type', 'text', 'sources', 'parent',
                  'related_argument', 'is_approved']
        widgets = {
            'premise_type': forms.RadioSelect,
            'related_argument': forms.TextInput,
        }

    def __init__(self, *args, **kwargs):
        super(PremiseEditForm, self).__init__(*args, **kwargs)
        queryset = (
            self.instance.argument.premises
                .exclude(pk=self.instance.pk)  # avoid self-loop
        )
        self.fields['parent'].queryset = queryset


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ["fallacy_type", "reason"]

    def clean(self):
        is_report_exist = Report.objects.filter(
            reporter=self.initial['reporter'],
            premise=self.initial['premise'],
            contention=self.initial['contention'],
            fallacy_type=self.cleaned_data['fallacy_type']
        ).exists()

        if is_report_exist:
            raise ValidationError(
                u'You have already reported %s fallacy for this premise.' % (
                    self.cleaned_data['fallacy_type']
                )
            )

        super(ReportForm, self).clean()

web/templates/premises/actions.html
{% load i18n %}
<form action="{% url "insert_premise" contention.slug premise.pk %}" method="get">
    <input type="submit" value="{% trans "add premise" %}"/>
</form>
<form action="{% url "delete_premise" contention.slug premise.pk %}" method="post">
    {% csrf_token %}
    <input type="submit" value="{% trans "remove" %}" class="delete_premise"/>
</form>

web/templates/premises/base_contention.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load gravatar %}

{% block title %}{{ serialized.title }} | {% trans "Argument Map" %}{% endblock %}

{% block extra-meta %}
    <meta property="og:description" content="{{ description }}"/>
    <meta name="canonical" content="{{ serialized.full_url }}"/>
{% endblock %}

{% block description %}{{ description }}{% endblock  %}

{% block body-attrs %} id="contention-detail"{% endblock %}

{% block header %}
    <header class="contention-detail-header">
        {% with channel=contention.channel %}
            {% if channel %}
            <div id="logo" class="contention-logo with-channel">
                <a href="{{ channel.get_absolute_url }}">argüman<img src="{% static "img/logo.png" %}" /></a>
                <a href="{{ channel.get_absolute_url }}" class="channel">/{{ contention.channel }}</a>
            </div>
            {% else %}
            <div id="logo" class="contention-logo">
                <a href="/">argüman<img src="{% static "img/logo.png" %}" /></a>
            </div>
            {% endif %}
        {% endwith %}
        <div class="header-block">
            <div class="sender">
                <h4>{% trans "sender" %}</h4>
                <a href="{% url "auth_profile" serialized.user.username %}">
                    {% gravatar contention.user 40 %}
                    {{ serialized.user.username|lower }}
                </a>
            </div>
        </div>
        <div class="header-block original-discourse">
            <h4>{% trans "source" %}</h4>
            <p>{% spaceless %}{% if serialized.owner %} 
                {{ serialized.owner }}
             {% elif serialized.sources %}
                {{ serialized.sources|urlizetrunc:30 }} 
            {% else %} 
                {% trans "Unspecified" %} 
            {% endif %}{% endspaceless %}</p>
        </div>
        <div class="header-block argument-actions">
            <ul>
                <li class="random-argument">
                    <a href="{% url "contentions_random" %}">
                        {% trans "RANDOM" %}
                        <img align="right" width="18" src="{% static "img/arrow-right.svg" %}" />
                    </a>
                </li>
                <li class="related-arguments">
                    <a href="{% url "contentions_random" %}">
                        {% trans "RELATED ARGUMENTS" %}
                        <img align="right" width="18" src="{% static "img/arrow-down.svg" %}" />
                    </a>
                </li>
            </ul>
        </div>
{#        <div class="header-block random-argument">#}
{#            <h4><a href="{% url "contentions_random" %}">{% trans "RANDOM" %}#}
{#                <img align="right" width="24" src="{% static "img/arrow-right.svg" %}" /></a></h4>#}
{#        </div>#}
{#        <div class="header-block related-arguments">#}
{#            <img align="right" width="24" src="{% static "img/arrow-down.svg" %}" />#}
{#            <h4><a href="#">{% trans "RELATED ARGUMENTS" %}</a></h4>#}
{#        </div>#}
        <div class="header-block share">
            <h4>{% trans "share" %}</h4>
            <p>
                <a target="_blank" href="https://www.facebook.com/sharer.php?u={{ serialized.full_url }}" class="tree-view active"> <img width="20" height="20" src="{% static "img/facebook.svg" %}" /> </a>
                <a target="_blank" href="http://twitter.com/home?status={{ serialized.title }} {{ serialized.full_url }}" class="list-view"> <img width="20" height="20" src="{% static "img/twitter.svg" %}" /> </a>
            </p>
        </div>
        <div class="header-block view">
            <h4>{% trans "view" %}</h4>
            <p>
                <a id="tree-view-button" href="?" class="tree-view active">     <img width="18" height="18" alt="{% trans "Tree" %}" src="{% static "img/tree.svg" %}" /> </a>
                <a id="list-view-button" href="?view=list" class="list-view">     <img width="20" height="20" alt="{% trans "List" %}" src="{% static "img/thread.svg" %}" /> </a>
            </p>
        </div>
    </header>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
{% endblock %}


{% block footer %}{% endblock %}

web/templates/premises/contention.html
{% load i18n %}
{% for contention in contentions %}
    <li>
        <div class="stats">
            <span class="because">{{ contention.because.count }} {% trans "because" %}</span>
            <span class="but">{{ contention.but.count }} {% trans "but" %}</span>
            <span class="however">{{ contention.however.count }} {% trans "however" %}</span>
        </div>
        <div class="info">
            <a class="main-contention" href="{{ contention.get_absolute_url }}">{{ contention.title }}</a>
            <div class="user">{% trans "sender:" %} <a href="{% url "auth_profile" contention.user.username %}">{{ contention.user }}</a></div>
        </div>
    </li>
{% endfor %}

web/templates/premises/contention_list.html
{% load i18n %}
{% load humanize %}
{% load gravatar  %}
{% load typogrify_tags %}

<ul class="argument-list">
    {% for contention in contentions %}
        {% with overview=contention.overview but=contention.but.count however=contention.however.count because=contention.because.count %}
        <li>
            {% if show_stats %}
            <div class="stats">
                <span class="because">{{ because }} {% trans "because" %}</span>
                <span class="but">{{ but }} {% trans "but" %}</span>
                <span class="however">{{ however }} {% trans "however" %}</span>
            </div>
            {% endif %}
            <div class="info">
                <h3><a class="main-contention {{ overview.status }}" href="{{ contention.get_absolute_url }}">{{ contention.title }}</a></h3>
                <div class="overview">
                    <div class="rate {{ overview.status }}">
                        {% if overview.status == 'objected' %}
                            %{{ overview.objection|floatformat }} {% trans "objection rate" %}
                        {% endif %}
                        {% if overview.status == 'supported' %}
                            %{{ overview.support|floatformat }} {% trans "support rate" %}
                        {% endif %}
                        {% if overview.status == 'neutral' %}
                            {% trans "Neutral support and objection rate." %}
                        {% endif %}
                    </div>
                    {% if show_last_premise %}
                    {% with contention.last_premise as last_premise %}
                    {% if last_premise %}
                    <div class="last-premises">
                        <div class="last-premise">
                            <a href="{{ last_premise.get_absolute_url }}">
                                {{ last_premise.text }}
                                {% if last_premise.related_argument %}
                                <p>{{ last_premise.related_argument }}</p>
                                {% endif %}
                            </a>
                        </div>
                    </div>
                    {% endif %}
                    {% endwith %}
                    {% endif %}
                    <div class="user">
                        {% with last_user=contention.last_user %}
                            <a href="{% url "auth_profile" last_user.username %}">
                                {% gravatar last_user 50 last_user.username %}
                                <span>{{ last_user.username|lower }}</span>
                            </a>
                        {% endwith %}
                        <time datetime="{{ contention.date_modification }}">({{ contention.date_modification|naturaltime }})</time>
                    </div>
                </div>
            </div>
        </li>
        {% endwith %}
    {% empty %}
        {% if keywords %}
            <li>{% trans "No results found." %}</li>
        {% endif %}
    {% endfor %}
    {% if has_next_page %}
    <li class="load-more">
        <a class="next" href="{{ next_page_url }}">{% trans "Load more" %}</a>
    </li>
    {% endif %}
</ul>

web/templates/premises/edit_contention.html
{% extends 'base.html' %}
{% load i18n %}
{% load premise_tags %}

{% block content %}
    <section class="container">
        <form action="?" method="post">
            <h2>{% trans "Edit Argument" %}</h2>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="{% trans "Update" %}" class="submit">
        </form>
        {% if form.instance|check_content_deletion %}
            <form action="{% url "contention_delete" form.instance.slug %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="{% trans "Remove the argument" %}" class="submit">
        </form>
        {% endif %}
    </section>
{% endblock %}

web/templates/premises/edit_premise.html
{% extends 'premises/new_premise.html' %}
{% load i18n %}

{% block content %}
    <section class="container">
        <form action="?" method="post">
            <h2>{% trans "Edit Premise" %}</h2>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="{% trans "Update" %}" class="submit">
        </form>
    </section>
{% endblock %}

web/templates/premises/list_view.html
{% extends "premises/base_contention.html" %}
{% load i18n %}
{% load static %}


{% block content %}
    <div id="app" class="list-view">
        <div class="main-contention">
            <h3 class="contention-header">
                {{ contention }}
            </h3>
            {% if user.is_authenticated and not parent_premise %}
            <a class="new-main-premise" href="{% url "new_premise" contention.slug %}?view=list">{% trans "add premise" %}</a>
            {% endif %}
        </div>
        <div class="thread">
            {% if parent_premise %}
            <div class="thread-item parent-premise">
                <a class="go-to-main-premise"
                   href="{{ parent_premise.get_parent.get_absolute_url }}?view=list">&lsaquo; {% trans "Go to parent premise" %}</a>
                {% include "premises/thread.html" with premise=parent_premise %}
                {% if premises.exists %}
                    <div class="parent-premise-info"></div>
                {% endif %}
            </div>
            {% endif %}
            {% for premise in premises.all %}
            <div class="thread-item">
                {% include "premises/thread.html" %}
            </div>
            {% endfor %}
        </div>
    </div>

    {% if user.is_anonymous %}
    {% include "auth/login_popup.html" %}
    {% endif %}

{% endblock %}

{% block footer %}{% endblock %}

web/templates/premises/new_contention.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <section class="container">
        <form action="{% url "new_argument" %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="{% trans "Save and continue to edit" %}" class="submit">
        </form>
    </section>
{% endblock %}

web/templates/premises/new_premise.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <section class="container new-premise">
        <form action="?view={{ view }}" method="post">
            {% if parent %}
                <div class="parent-premise">
                    <strong>{% trans "The parent premise:" %}</strong>
                    <p>{{ parent.text }}</p>
                </div>
            {% endif %}
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="{% trans "Submit" %}" class="submit">
        </form>
    </section>
{% endblock %}

{% block extra-scripts %}
    <script type="text/javascript">
    $(function () {
        var relatedArgumentLabel = "{{ premise.related_argument.title }}";

        var textarea = $("#id_text"),
            container = $("<div>", {
                "class": "remained-char"
            }).appendTo(textarea.parent())
              .html("{% trans "Characters remaining: " %}"),
            remained = $("<span>").appendTo(container);
        var update = function (event) {
            var max = parseInt(textarea.attr("maxlength")),
                _remained = max - textarea.val().length;
            remained.html(_remained);
        };
        textarea.keyup(update);
        update();

        var relatedArgument = $('#id_related_argument');

        var selectArgument = function (label) {
            var selectedArgument = $("<div />", {
                'class': 'selected-argument'
            }).html(
                label
            ).append(
                $("<a />")
                 .html(
                    '{% trans "(change)" %}'
                 ).on('click', function (event) {
                    event.preventDefault();
                    relatedArgument.val("").show();
                    selectedArgument.remove();
                 }.bind(this))
            );
            relatedArgument.hide().after(selectedArgument);
        };

        relatedArgument.autocomplete({
            source: function(search, callback) {
                $.getJSON("{% url "contentions_search" %}", {
                    keywords: search.term,
                    json: true
                }, callback);
            },
            select: function(event, ui) {
                $(this).val(ui.item.id);
                selectArgument(ui.item.label);
                return false;
            }
        });

        if (relatedArgument.val()) {
            selectArgument(relatedArgumentLabel);
        }
    });
    </script>
{% endblock %}

web/templates/premises/report.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <section class="container">
        <form action="?view={{ view }}" method="post">
            <label>{% trans "The premise:" %}</label>
            <div class="fallacy-premise">
                <p>{{ premise.text }}</p>
            </div>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="{% trans "Report Fallacy" %}" class="submit">
        </form>
    </section>
{% endblock %}

web/templates/premises/tree.html
{% load i18n %}
{% load humanize %}
<ul class="tree" data-level="{{ level }}">
    {% for premise in premises %}
        <li id="premise-{{ premise.id }}" class="tree-branch">
            <div class="connector branch-connector{% if premises|length < 2 %} branch-single{% endif %}"></div>
            {% include "premises/premise.html" %}
            {% if premise.children %}
            {% if level == 1 and premises|length > 5 %}
                <div data-load-partial="?partial={{ premise.id }}&level={{ level|add:1 }}"></div>
            {% else %}
                {% with template_name="premises/tree.html" premises=premise.children level=level|add:1 %}
                    {% include template_name %}
                {% endwith %}
            {% endif %}
            <div class="connector child-connector"></div>
            {% endif %}
        </li>
    {% endfor %}
    {% if premises %}
        <li class="connector tree-connector"></li>
        <li class="collapsible-preview">{{ premises|length|add:-1 }} {% trans "branch" %}</li>
        <li class="collapse-button">‒</li>
    {% endif %}
</ul>