web/api/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns(
    '',
    url(r'^v1/', include('api.v1.urls')),
)

web/main/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.sitemaps import views as sitemaps_views
from django.views.decorators.cache import cache_page

from blog.sitemaps import BlogSitemap
from nouns.views import ChannelDetail
from profiles.sitemaps import ProfileSitemap
from premises.sitemaps import ArgumentSitemap, PremiseSitemap

admin.autodiscover()

sitemaps = {
    'blog': BlogSitemap(),
    'user': ProfileSitemap(),
    'argument': ArgumentSitemap(),
    'premise': PremiseSitemap()
}

urlpatterns = patterns('',
    url(r'^', include('newsfeed.urls')),
    url(r'^', include('premises.urls')),
    url(r'^', include('profiles.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^nouns/', include('nouns.urls')),
    url(r'^channels/(?P<slug>[-\w]+)$',
        ChannelDetail.as_view(), name="channel_detail"),
    url(r'^', include('social_auth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include('api.urls')),

    # Sitemap
    url(r'^sitemap\.xml$',
        cache_page(86400)(sitemaps_views.index),
        {'sitemaps': sitemaps, 'sitemap_url_name': 'sitemaps'}),
    url(r'^sitemap-(?P<section>.+)\.xml$',
        cache_page(86400)(sitemaps_views.sitemap),
        {'sitemaps': sitemaps}, name='sitemaps'),
)

web/nouns/urls.py
from django.conf.urls import patterns, url
from nouns.views import NounDetail, RelationCreate, ChannelDetail

urlpatterns = patterns('',
    url(r'^(?P<slug>[-\w]+)/$', NounDetail.as_view(), name="nouns_detail"),
    url(r'^(?P<slug>[-\w]+)/new-relation$', RelationCreate.as_view(), name="new_relation"),
)

web/nouns/models.py
from uuid import uuid4
from unidecode import unidecode

from django.db import models
from django.utils.encoding import smart_unicode
from django.conf import settings
from django.template.defaultfilters import slugify
from django.utils.functional import curry
from django.utils.translation import ugettext_lazy as _, get_language
from anora.templatetags.anora import CONSONANT_SOUND, VOWEL_SOUND
from i18n.utils import normalize_language_code

from nouns.utils import get_synsets, get_lemmas, from_lemma


class Noun(models.Model):
    text = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, blank=True)
    language = models.CharField(max_length=25)
    is_active = models.BooleanField(default=True)

    class Meta:
        unique_together = (("text", "language"),)

    def __unicode__(self):
        return smart_unicode(self.text).title()

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = slugify(unidecode(self.text))
            duplications = Noun.objects.filter(slug=slug,
                                               language=self.language)
            if duplications.exists():
                self.slug = "%s-%s" % (slug, uuid4().hex)
            else:
                self.slug = slug
        return super(Noun, self).save(*args, **kwargs)

    @classmethod
    def from_synset(cls, synset):
        lemmas = synset.lemma_names()
        text = lemmas[0]
        keywords = lemmas[1:]
        noun, created = cls.objects.get_or_create(
            text=from_lemma(text),
            defaults={
                'is_active': False,
                'language': normalize_language_code(get_language())
            })
        for keyword in keywords:
            noun.add_keyword(from_lemma(keyword))
        return noun

    def update_with_wordnet(self, update_antonyms=True):
        synsets = get_synsets(self.text)

        if not synsets:
            return

        for synset in synsets:
            path = synset.hypernym_paths()[0]
            parents = path[:-1]
            parent = self
            for hypernym in reversed(parents):
                noun = Noun.from_synset(hypernym)
                parent.add_hypernym(noun)
                parent = noun

            for holonym in synset.part_holonyms():
                noun = Noun.from_synset(holonym)
                self.add_holonym(noun)

            for holonym in synset.member_holonyms():
                noun = Noun.from_synset(holonym)
                self.add_holonym(noun)

        for lemma in get_lemmas(self.text):
            if lemma != self.text:
                self.add_keyword(lemma)

        if not update_antonyms:
            return

        for synset in synsets:
            for lemma in synset.lemmas():
                for antonym in lemma.antonyms():
                    noun = Noun.from_synset(antonym.synset())
                    self.add_antonym(noun)
                    noun.update_with_wordnet(update_antonyms=False)

    def add_keyword(self, text):
        keyword, created = self.keywords.get_or_create(text=text)
        return keyword

    def active_keywords(self):
        return self.keywords.filter(is_active=True)

    def active_contentions(self):
        language = normalize_language_code(get_language())
        return self.contentions.filter(
            is_published=True,
            language=language
        ).order_by('?')

    def indirect_contentions(self):
        from premises.models import Contention  # to avoid circular import
        language = normalize_language_code(get_language())
        nouns = self.out_relations.values_list('target', flat=True)
        return Contention.objects.filter(
            language=language,
            is_published=True,
            nouns__in=nouns
        ).order_by('?')

    @models.permalink
    def get_absolute_url(self):
        return 'nouns_detail', [self.slug]

    def serialize(self):
        return {
            'title': self.text,
            'absolute_url': self.get_absolute_url()
        }

    def hypernyms(self):
        return self.out_relations.filter(relation_type='hypernym')

    def hyponyms(self):
        return self.in_relations.filter(relation_type='hypernym')

    def add_relation(self, target, relation_type=None):
        relation, created = (
            self.out_relations.get_or_create(
                target=target, relation_type=relation_type)
        )
        return relation

    add_hypernym = curry(add_relation, relation_type="hypernym")
    add_holonym = curry(add_relation, relation_type="holonym")
    add_antonym = curry(add_relation, relation_type="antonym")


class Keyword(models.Model):
    """
    Keywords for matching contentions.
    """
    noun = models.ForeignKey(Noun, related_name="keywords")
    text = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)

    def __unicode__(self):
        return smart_unicode(self.text)


class Relation(models.Model):
    """
    Holds the relationships of contentions.

        - is a (hypernym)
        - part of (holonym)
        - opposite (antonym)
        - same_as (synonym)

    """
    HYPERNYM = "hypernym"
    HOLONYM = "holonym"
    ANTONYM = "antonym"
    HYPONYM = "hyponym"
    MERONYM = "meronym"

    TYPES = (
        (HYPERNYM, _('is a')),
        (HOLONYM, _('part of')),
        (ANTONYM, _('opposite with')),
    )

    source = models.ForeignKey(Noun, related_name="out_relations")
    target = models.ForeignKey(Noun, related_name="in_relations")
    relation_type = models.CharField(max_length=25, choices=TYPES)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    is_active = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return smart_unicode(self.relation_type)

    def reverse_type(self):
        return {
            Relation.HYPERNYM: Relation.HYPONYM,
            Relation.HOLONYM: Relation.MERONYM,
            Relation.ANTONYM: Relation.ANTONYM
        }.get(self.relation_type)

    def get_reverse_type_display(self):
        return {
            Relation.HYPONYM: _("whole of"),
            Relation.MERONYM: _("whole of"),
            Relation.ANTONYM: _("opposite with")
        }.get(self.reverse_type())

    def relation_type_label(self):
        if (self.relation_type == Relation.HYPERNYM
                and self.target.language == 'en'):
            text = unicode(self.target)
            return ('is an' if not CONSONANT_SOUND.match(text)
                               and VOWEL_SOUND.match(text)
                    else 'is a')
        return self.get_relation_type_display()


class Channel(models.Model):
    title = models.CharField(max_length=255)
    slug = models.CharField(max_length=255)
    nouns = models.ManyToManyField('Noun', null=True, blank=True)
    order = models.IntegerField()
    language = models.CharField(max_length=255, blank=True, null=True)
    is_featured = models.BooleanField(max_length=255, default=False)

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = slugify(unidecode(self.text))
            self.slug = slug
        return super(Channel, self).save(*args, **kwargs)

    def __unicode__(self):
        return smart_unicode(self.title)

    @models.permalink
    def get_absolute_url(self):
        return 'channel_detail', [self.slug]

    def serialize(self):
        return {
            'title': self.title,
            'absolute_url': self.get_absolute_url()
        }

web/nouns/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils.translation import get_language

from i18n.utils import normalize_language_code
from premises.mixins import FormRenderer
from nouns.models import Relation, Noun


class RelationCreationForm(FormRenderer, forms.ModelForm):
    target_noun = forms.CharField()
    relation_type = forms.ChoiceField(
        choices=Relation.TYPES, widget=forms.RadioSelect)

    class Meta:
        model = Relation
        fields = ['relation_type']

    def clean_target_noun(self):
        target_noun = self.cleaned_data['target_noun']
        return (target_noun
                 .lower()
                 .strip())

    def get_target(self):
        target_noun = self.cleaned_data['target_noun']

        try:
            noun = Noun.objects.get(
                text=target_noun,
                language=normalize_language_code(get_language())
            )
        except Noun.DoesNotExist:
            noun = Noun.objects.create(
                text=target_noun,
                is_active=False,
                language=normalize_language_code(get_language())
            )

        return noun

web/nouns/views.py
from datetime import timedelta, datetime
from django.contrib.auth.models import User
from django.db.models import Count, Q, Sum, F
from django.shortcuts import get_object_or_404, redirect
from django.utils.translation import get_language
from django.views.generic import DetailView, CreateView, ListView
from i18n.utils import normalize_language_code
from nouns.models import Noun, Relation, Channel
from nouns.forms import RelationCreationForm
from premises.models import Contention
from premises.views import HomeView
from profiles.mixins import LoginRequiredMixin
from profiles.models import Profile


class NounDetail(DetailView):
    queryset = (Noun
                .objects
                .prefetch_related('contentions')
                .select_related('contentions__user')
                .order_by('-date_creation'))
    template_name = "nouns/detail.html"
    partial_template_name = "nouns/partial.html"
    context_object_name = "noun"

    def get_template_names(self):
        if self.request.GET.get('partial'):
            return [self.partial_template_name]
        return [self.template_name]

    def get_context_data(self, **kwargs):
        contentions = (self.get_object().active_contentions())
        indirect_contentions = (self.get_object().indirect_contentions())
        source = self.request.GET.get('source')
        if source:
            contentions = contentions.exclude(id=source)
            indirect_contentions = indirect_contentions.exclude(id=source)
        return super(NounDetail, self).get_context_data(
            contentions=contentions,
            indirect_contentions=indirect_contentions,
            **kwargs)

    def get_object(self, queryset=None):
        return get_object_or_404(
            self.queryset,
            slug=self.kwargs['slug'],
            language=normalize_language_code(get_language())
        )


class RelationCreate(LoginRequiredMixin, CreateView):
    model = Relation
    template_name = "nouns/new_relation.html"
    form_class = RelationCreationForm
    initial = {
        'relation_type': Relation.HYPERNYM
    }

    def form_valid(self, form):
        form.instance.source = self.get_noun()
        form.instance.target = form.get_target()
        form.instance.user = self.request.user
        form.instance.is_active = False
        form.save()
        return redirect(form.instance.source)

    def get_context_data(self, **kwargs):
        noun = self.get_noun()
        return super(RelationCreate, self).get_context_data(
            noun=noun, **kwargs)

    def get_noun(self):
        return get_object_or_404(
            Noun,
            slug=self.kwargs.get('slug'),
            language=normalize_language_code(get_language())
        )


class ChannelDetail(HomeView):
    template_name = "nouns/channel_detail.html"
    paginate_by = 20
    context_object_name = "contentions"

    def get_channel(self):
        language = normalize_language_code(get_language())
        return get_object_or_404(Channel, slug=self.kwargs['slug'],
                                 language=language)

    def get_context_data(self, **kwargs):
        channel = self.get_channel()
        return super(ChannelDetail, self).get_context_data(
            active_users=self.get_active_users(),
            channel=channel, **kwargs)

    def get_contentions(self, paginate=True):
        channel = self.get_channel()
        nouns = channel.nouns.all()
        contentions = (Contention
                       .objects
                       .language()
                       .filter(is_published=True,
                               nouns__in=nouns)
                       .distinct()
                       .order_by("-date_modification"))

        if paginate:
            contentions = (contentions[self.get_offset(): self.get_limit()])

        return contentions

    def get_active_users(self):
        channel = self.get_channel()
        nouns = channel.nouns.all()
        return Profile.objects.filter(
            user_premises__argument__nouns__in=nouns,
            user_premises__argument__is_published=True,
            user_premises__date_creation__gte=datetime.today() - timedelta(days=30)
        ).annotate(
            score=Count('user_premises__argument', distinct=True)
        ).order_by(
            '-score'
        )[:5]

web/templates/nouns/channel_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load humanize %}
{% load gravatar %}

{% block title %}{{ channel }}{% endblock %}

{% block content %}

<div class="container channel-index">
    {% include "partials/channel_list.html" %}

    <h3>{{ channel }}</h3>
    <ul class="channel-active-users">
    <li class="title"><span>{% trans "Regular users" %}</span></li>
    {% for active_user in active_users %}
        <li><a href="{{ active_user.get_absolute_url }}">{% gravatar active_user 60 %}</a></li>
    {% endfor %}
    </ul>
    <div class="channel-contentions">
        {% include "premises/contention_list.html" with show_stats=True %}
    </div>
</div>
{% endblock %}

{% block extra-scripts %}
{% include "infinity-pagination.html" %}
{% endblock %}

web/templates/nouns/detail.html
{% extends "base.html" %}
{% load i18n %}
{% load humanize %}
{% load gravatar %}

{% block title %}{{ noun }}{% endblock %}

{% block content %}
<div class="container">
    <div class="noun-tree">
        <h3>{{ noun }}</h3>
        <ul class="relations">
            {% for relation in noun.out_relations.all %}
            <li class="{{ relation.relation_type }} relation">
                <span>{{ relation.relation_type_label }}</span>
                <a href="{{ relation.target.get_absolute_url }}">{{ relation.target }}</a>
                {% if relation.user %}
                    <a class="sender" href="{{ relation.user.get_absolute_url }}">{% gravatar relation.user 20 %}</a>
                {% endif %}
                {% if relation.target.hyponyms.exists %}
                <ul class="hyponyms">
                    {% for hyponym in relation.target.hyponyms.all %}
                    {% if hyponym.source != noun %}
                    <li><a href="{{ hyponym.source.get_absolute_url }}">{{ hyponym.source }}</a></li>
                    {% endif %}
                    {% endfor %}
                </ul>
                {% endif %}
            </li>
            {% endfor %}
            {% for relation in noun.in_relations.all %}
            {% if relation.relation_type != "antonym" %}
            <li class="{{ relation.reverse_type }} relation">
                <span>{{ relation.get_reverse_type_display }}</span>
                <a href="{{ relation.source.get_absolute_url }}">{{ relation.source }}</a>
            </li>
            {% endif %}
            {% endfor %}
            <li class="create relation"><a href="{% url "new_relation" noun.slug %}">{% trans "add new relation" %}</a></li>
        </ul>
        <ul class="contentions relations">
            {% for contention in noun.active_contentions.all %}
            <li class="argument relation">
                <a class="contention-link" href="{% url "contention_detail" contention.slug %}">{{ contention.title }}</a>
                <ul class="argument-stats">
                    <li>
                    <a href="{{ contention.user.get_absolute_url }}">@{{ contention.user }}</a> {{ contention.date_creation|naturaltime }}
                    </li>
                </ul>
            </li>
            {% endfor %}
            <li class="create relation"><a href="{% url "new_argument" %}">{% trans "create an argument" %}</a></li>
        </ul>
    </div>
</div>
{% endblock %}

web/templates/nouns/new_relation.html
{% extends "base.html" %}
{% load i18n %}
{% load humanize %}

{% block content %}
<div class="container">
    <form action="{% url "new_relation" noun.slug %}"
          method="post" class="new-relation-form">
    {% csrf_token %}
    <h2>{% trans "New Relation" %}</h2>
    <div class="relation-source">
        <span>{{ noun }}</span>
    </div>
    <div class="relation-type">
        {{ form.relation_type }}
    </div>
    <div class="relation-target">
        {{ form.target_noun }}
        <label>{% trans "Target noun (Singular)" %}</label>
    </div>
    <div class="relation-type-examples">
        <h3>{% trans "Relation types" %}</h3>
        {% blocktrans trimmed %}
            <p><b>Is a (hypernym and hyponym)</b> A type-of relationship between two types. For example
                <i>Organic Process</i> is the hypernym of <i>Evolution</i>.</p>
        {% endblocktrans %}
        {% blocktrans trimmed %}
            <p><b>Part of (holonymy and meronymy)</b> A part/whole relationship between two types.
                For example <i>Natural Selection</i> is the part of <i>Evolution</i></p>
        {% endblocktrans %}
        {% blocktrans trimmed %}
        <p><b>Opposite with (antonym)</b> The opposite meaning of the type.
            For example, <i>Evolution</i> and <i>Devolution</i></p>
        {% endblocktrans %}
    </div>
    <div class="form-footer">
        <input type="submit" value="{% trans "Submit" %}" class="submit" />
    </div>
    </form>
</div>
</div>
{% endblock %}

web/templates/nouns/partial.html
{% load i18n %}
<h3>{{ noun }}</h3>
<ul class="relations">
{% for relation in noun.out_relations.all %}
<li class="{{ relation.relation_type }} relation">
    <span>{{ relation.relation_type_label }}</span>
    <a href="{{ relation.target.get_absolute_url }}">{{ relation.target }}</a>
</li>
{% endfor %}
{% if not noun.out_relations.exists  %}
<li class="create relation"><a href="{% url "new_relation" noun.slug %}">{% trans "add new relation" %}</a></li>
{% endif %}
</ul>

{% if contentions.exists or indirect_contentions.exists %}
<h3>{% trans "Arguments" %}</h3>
<ul class="contentions relations">
    {% for contention in contentions|slice:":3" %}
    <li class="argument relation">
        <a class="contention-link" href="{% url "contention_detail" contention.slug %}">{{ contention.title }}</a>
    </li>
    {% endfor %}
    {% for contention in indirect_contentions|slice:":3" %}
    <li class="argument relation">
        <a class="contention-link" href="{% url "contention_detail" contention.slug %}">{{ contention.title }}</a>
    </li>
    {% endfor %}
</ul>
{% endif %}